version: "3.9"
services:
	ragemp_server:
		build: .
		hostname: "ragemp_server"
		container_name: "ragemp_server"
		ports:
			- "22005:22005/udp"
			- "22006:22006"
		tty: true

networks:
	default:
		external:
			name: ragemp_network